on: pull_request
name: ScanAPI Examples
jobs:
  poke-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6.x
      - name: Poetry Setup
        uses: snok/install-poetry@v1.1.1
        with:
          version: 1.0.9
      - name: Checkout ScanAPI repository
        uses: actions/checkout@v2
      - name: Checkout ScanAPI Examples repository
        uses: actions/checkout@v2
        with:
          repository: scanapi/examples
          path: examples
      - name: Install Dependencies
        run: poetry install
      - name: Run ScanAPI for PokeAPI
        run: "poetry run scanapi run ./examples/pokeapi/scanapi.yaml -c ./examples/pokeapi/scanapi.conf -o pokeapi.html"
      - name: Upload PokeAPI ScanAPI Report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: PokeAPI ScanAPI Report
          path: pokeapi.html

  httpbin-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6.x
      - name: Poetry Setup
        uses: snok/install-poetry@v1.1.1
        with:
          version: 1.0.9
      - name: Checkout ScanAPI repository
        uses: actions/checkout@v2
      - name: Checkout ScanAPI Examples repository
        uses: actions/checkout@v2
        with:
          repository: scanapi/examples
          path: examples
      - name: Install Dependencies
        run: poetry install
      - name: Run ScanAPI for httpbin.org
        run: "poetry run scanapi run ./examples/httpbin-api/httpbin.yaml -c ./examples/httpbin-api/scanapi.conf -o httpbin.html"
      - name: Upload httpbin.org ScanAPI Report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: httpbin.org ScanAPI Report
          path: httpbin.html

  demo-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6.x
      - name: Poetry Setup
        uses: snok/install-poetry@v1.1.1
        with:
          version: 1.0.9
      - name: Checkout ScanAPI repository
        uses: actions/checkout@v2
      - name: Checkout ScanAPI Examples repository
        uses: actions/checkout@v2
        with:
          repository: scanapi/examples
          path: examples
      - name: Install Dependencies
        run: poetry install
      - name: Run ScanAPI for Demo API
        env:
          BASE_URL: "http://demo.scanapi.dev/api/v1/"
          USER: "guest"
          PASSWORD: "demoapi123"
        run: "poetry run scanapi run ./examples/demo-api/scanapi.yaml -c ./examples/demo-api/scanapi.conf -o demo-api.html"
      - name: Upload Demo API ScanAPI Report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Demo API ScanAPI Report
          path: demo-api.html
